CREATE DATABASE Pessoas
USE Pessoas

CREATE TABLE Pessoas (
	IdPessoa INT PRIMARY KEY IDENTITY,
	Nome	 VARCHAR(100)
)

CREATE TABLE Telefones (
	IdTelefone INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(200),
	IdPessoa INT FOREIGN KEY REFERENCES Pessoas(IdPessoa)
)

CREATE TABLE Emails (
	IdEmail INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(200),
	IdPessoa INT FOREIGN KEY REFERENCES Pessoas(IdPessoa)
)

CREATE TABLE CNH (
	IdCNH INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(200),
	IdPessoa INT FOREIGN KEY REFERENCES Pessoas(IdPessoa)
)